### PR TITLE
shared activity transition

### PR DESCRIPTION
**Pull request by ByteHamster**

### CODE REVIEW

**Comment by grote** [comment]
Awesome, thanks a lot for fixing the transition! :)

**Comment by grote** [comment]
I noticed a "jump" at the bottom of the card during the transition. I guess that is super difficult to fix, right?

**Comment by ByteHamster** [comment]
> Why did you remove the CoordinatorLayout here? Did the transition not work with it?

I guess it's a bug in `CoordinatorLayout`:
After returning back to TripsActivity, the list scrolled randomly up or down by the height of the `Toolbar`.

> I noticed a "jump" at the bottom of the card during the transition. I guess that is super difficult to fix, right?

I tried to fix that but failed. Anyway, I think it looks much better with the animation ;)

**Comment by grote** [comment]
Alright, thanks! Merged.

**Pull request closed without merging**
