### PR TITLE
Don't post screenshots

### PR DESCRIPTION
**Pull request by schildbach**

### CODE REVIEW

**Comment by schildbach** [comment]
I'm afraid I don't sign CLAs.

**Comment by grote** [comment]
I don't think a CLA is needed for such a small change, but I am worried that users might not know what a stacktrace is. Maybe better say "copy the text above"?

People also complain about the URL being wrong. What is the right one that should be used?

**Comment by schildbach** [comment]
I'd say `https://github.com/schildbach/public-transport-enabler/issues` is what should be linked to.

**Comment by TheLastProject** [comment]
Why not just remove the instructions and add a title and body GET param to the new issue URL so it gets prefilled with the correct data? https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters

**Comment by ialokim** [comment]
This has been resolved with #625.

**Pull request closed without merging**
