### PR TITLE
Add Quebec (Canada) region.

### PR DESCRIPTION
**Pull request by chimo**

### CODE REVIEW

**Comment by chimo** [comment]
(refs. #144)

**Comment by baldurmen** [comment]
:D this is great.

I'm curious about naming the cities though. If you look at the data (https://navitia.opendatasoft.com/explore/dataset/ca-qc/table/), way more cities are supported than just Quebec, Montreal, Laval & Sherbrooke.

But then again, these are the only cities marked in "Geographic Area". Does it mean we'll still be able to see buses and trains from Chambly or in the Outaouais region even though cities won't be added?

**Comment by grote** [comment]
Awesome! Looks good!

Have you seen the Ontario logo in the navigation drawer? The ON can't really be seen. I guess it will be similar with QC. Do you think it will still look good when the text is moved more towards the center?

@baldurmen you should be able to get results for all agencies listed on that page. If you want to know what exactly is in there, you can open the linked zip files and peek inside the data yourself or you wait for the next release to use Transportr to explore the data.

TLEM in England has a pretty long list of cities as well. I guess there's no reason to not add at least more of the bigger cities to the list if they are indeed supported. You could also describe it differently like "All major cities supported" (if that's true) or something similar. @chimo what do you think?

**Comment by chimo** [comment]
> I'm curious about naming the cities though. If you look at the data (https://navitia.opendatasoft.com/explore/dataset/ca-qc/table/), way more cities are supported than just Quebec, Montreal, Laval & Sherbrooke.

@baldurmen  Ah yes, I didn't realize; I copied the (incomplete, turns out) list from here: https://navitia.opendatasoft.com/explore/dataset/ca-qc/ I'll add the others.

> Have you seen the Ontario logo in the navigation drawer? The ON can't really be seen. I guess it will be similar with QC. Do you think it will still look good when the text is moved more towards the center?

@grote Good catch, I'll try moving the text.

**Comment by grote** [comment]
Thanks a lot! :)

Would you mind also changing the logo for Ontario and letting me know when you personally feel the status of those providers can be moved from `alpha` to `beta`?
I'm not living there and not using them, so for me it is hard to judge.

**Comment by chimo** [comment]
Done in #167 !

I've been using the Ontario (well, Ottawa more specifically, I suppose) and I'm okay bumping it to beta.
Maybe @baldurmen can tell us about their experience with the Quebec region and if it's good we can do the same for that region?

**Comment by baldurmen** [comment]
> I've been using the Ontario (well, Ottawa more specifically, I suppose) and I'm okay bumping it to beta.
> Maybe @baldurmen can tell us about their experience with the Quebec region and if it's good we can do the same for that region?

Hmmm, I can _try_ building it but I can't guaranty anything. I'll post
updates here.

**Comment by grote** [comment]
@baldurmen you can also wait for the next release and let us know at any time.

**Comment by baldurmen** [comment]
Hmm, I think I'll do that.

**Pull request merged**
