### PR TITLE
Fix German translation

### PR DESCRIPTION
**Pull request by pjaap**
Found a translation mistake.

### CODE REVIEW

**Comment by ialokim** [comment]
Thanks, good spot! We are managing the translations for Transportr as a Transifex project. If you would be interested in joining the German translation team, feel free to sign up there. More information can be found on [our website](https://transportr.app/contribute/#translating-into-your-language).

If, however, you just want to get this little fix included in Transportr and don't want to get a new account at another service, I could change the translation at Transifex. Just report back what you would prefer.

**Comment by ialokim** [comment]
Btw, I even would prefer "wenigste Umstiege" instead of "geringste".

**Comment by pjaap** [comment]
Hi! Thanks for the feedback. I registered at Transifex (with my github profile), but cannot join the "German" Transportr Team. Do I need a confirmation?

**Comment by ialokim** [comment]
I've just accepted you.

**Comment by pjaap** [comment]
Thanks! I *think* I fixed it now in Transifex :)

**Pull request closed without merging**
