### PR TITLE
Add NegentweeProvider for 9292.nl

### PR DESCRIPTION
**Pull request by full-duplex**
This updates public-transport-enabler to add a new provider for 9292.nl, which contains all public transport in The Netherlands. I've been using it sporadically with a local build for the last weeks without any problems, but I've marked it BETA anyway.

(I've explained your comment about the `Line.label` here: https://github.com/schildbach/public-transport-enabler/pull/129)

### CODE REVIEW

**Comment by full-duplex** [comment]
Oops, just after I opened this PR I got a notification that you already added this provider. The only difference is that I pass the correct language to the provider based on locale, so you might want to integrate that.

**Comment by grote** [comment]
Oops, sorry for the duplicate work. I didn't realize you were planing a PR. Do you mind updating yours or making a new one for the correct language?

**Comment by grote** [comment]
Actually, I see that you are targettng the v1 branch which is great, because I didn't add it there.

**Comment by grote** [comment]
Would you mind replacing the PNG graphic with the XML vector drawable from master? Then this is good to go into v1.

**Comment by full-duplex** [comment]
It's using the vector logo from the v2 branch now.

**Comment by grote** [comment]
Thanks! :)

**Pull request merged**
