### PR TITLE
Add support for California transit systems.

### PR DESCRIPTION
**Pull request by n76**
Finally figured out how to build this project. :)

Along with changes in the [public-transport-enabler](https://github.com/schildbach/public-transport-enabler/pull/133), this seems to work at least as far as my local Orange County Transit Authority (OCTA) system is concerned. I haven't yet checked for the other transit systems in the source data.

Signed-off-by: Tod Fitch <Tod@FitchDesign.com>

### CODE REVIEW

**Comment by grote** [comment]
Thanks for the PR! Looks good to me.

Although this might work locally for you, it still requires your PR for public-transport-enabler to be merged, before it will work here.

**Comment by n76** [comment]
Understood.

The public-transport-enabler is maintained by a different person, so it may take a while. Looks like the Oregon changes took nearly 7 months to get into the code and are not yet on a released version of Transportr (they do show up in my debug build). I understand how this works as I've got an open source project or two where I haven't made the time to make requested changes.

**Comment by grote** [comment]
Indeed! I wish you the best of luck that your PTE PR needs less than 7 months to get merged ;)

**Comment by grote** [comment]
Looks like this PR is changing lots of unrelated files now.

**Comment by n76** [comment]
You changed a lot of files and the merge did not go as smoothly as I'd hoped. :)

FWIW when I build the master branch (labeled as something like v2 preview) it is pretty non-functional. v1.1.7 builds and runs fine for me (with the equivalent changes merged into it). Thank you for your great work!

I will continue to update this PR until the transport enabler change it needs it merged.

**Comment by grote** [comment]
The master branch is where development for v2 happens which probably takes a lot of time to be released stable. If you want support for California earlier, you need to target the v1 branch with your PR instead.

**Comment by n76** [comment]
If the PTE PR occurs before you release a v2 branch then I'll make a new PR for your v1 branch. . .

**Comment by grote** [comment]
There is now a PTE staging project that can be used to get this into transportr. @xamanu has more information.

**Comment by n76** [comment]
> There is now a PTE staging project that can be used to get this into transportr. @xamanu has more information.

I took a quick look at the github home page for @xamanu and did not see anything about a PTE staging project. Can you give me a direct link? Thanks!

**Comment by xamanu** [comment]
You can find the repository here: https://gitlab.com/opentransitmap/public-transport-enabler

We are exclusively taking in pull requests filed to [the upstream public-transport-enabler](https://github.com/schildbach/public-transport-enabler) on request. This allows them to be integrated into more quickly into Transportr.

@n76, do you want me to merge in your pull request https://github.com/schildbach/public-transport-enabler/pull/164?

**Comment by n76** [comment]
@xamanu If you could merge my pull request in that would be wonderful.

It has been so long since I looked at the pull requests for PTE and Transportr that I'd it might take me a while to do it correctly.

Thanks!

**Comment by xamanu** [comment]
[It's in](https://gitlab.com/opentransitmap/public-transport-enabler/commit/4493e6a71fb6a941cb2ef21f6837b92d93f62436).

**Comment by n76** [comment]
This pull request needs to be reworked to resolve some conflicts. Should I target the master branch or the v1 branch for that?

**Comment by grote** [comment]
I would target `master` branch as the `v1` branch will soon be dropped and probably won't see another release.

**Comment by n76** [comment]
Replaced by newer pull request https://github.com/grote/Transportr/pull/392

**Pull request closed without merging**
