### PR TITLE
Network Security Configuration

### PR DESCRIPTION
**Pull request by hoejmann**
Should hopefully resolve errors such as:

```
java.net.UnknownServiceException: CLEARTEXT communication to fahrplan.oebb.at not permitted by network security policy
okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
```
#
```
java.net.UnknownServiceException: CLEARTEXT communication to mobilapps.rejseplanen.dk not permitted by network security policy
okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)

```

### CODE REVIEW

**Comment by grote** [comment]
Thanks! Did you check if oeffi is doing the same thing? Is there any way to just allow clear text traffic for providers that don't use https?

**Comment by hoejmann** [comment]
It is the default setup as defined on https://developer.android.com/training/articles/security-config

```
The default configuration for apps targeting Android 7.0 (API level 24) to Android 8.1 (API level 27) is as follows:

<base-config cleartextTrafficPermitted="true">
    <trust-anchors>
        <certificates src="system" />
    </trust-anchors>
</base-config>
```

From what I see in the documentation, it would require a rather extensive list of subdomain based rules - not sure if there is some clever way of doing it.

```
 <domain-config cleartextTrafficPermitted="false">
        <domain includeSubdomains="true">secure.example.com</domain>
  </domain-config>
```

**Comment by grote** [comment]
Thanks for checking. In this case, it is probably infeasible to manually maintain cleartexts hosts and we have to enable cleartext for everything.

**Comment by grote** [comment]
Could you please state whether you accept the CLA?

**Comment by hoejmann** [comment]
I accept the CLA.

**Comment by grote** [comment]
@cla-bot[bot] check

**Comment by grote** [comment]
Thanks again!

**Pull request merged**
