### PR TITLE
Replace deprecated getColor() method with ContextCompat.getColor().

### PR DESCRIPTION
**Pull request by johnjohndoe**

### CODE REVIEW

**Comment by grote** [comment]
I didn't know about ContextCompat, thanks! However, Travis failed to build your PR. Do you want to look into this?

**Comment by johnjohndoe** [comment]
Ups, fixed that. :angel:

**Comment by grote** [comment]
Merged, thanks a lot! Do you want to do the same with `context.getResources().getDrawable()`?

**Comment by johnjohndoe** [comment]
Here you go .. #161

**Comment by grote** [comment]
Wow that was fast! :)

**Comment by johnjohndoe** [comment]
I just thought I serve it peace by peace so I can rebase on HEAD and you can merge it linear.

**Comment by grote** [comment]
Very much appreciated, although a little heads up is nice, as I almost started to do it myself.
I'm curious why you chose these things to contribute. Is there a problem coming up when using the deprecated API here?

**Comment by johnjohndoe** [comment]
I just saw that Google finally added the wrapper. Since I was dealing with API workarounds myself in other projects I thought it would be nice to contribute it here.

**Pull request closed without merging**
