### PR TITLE
Hide walking route unless it's the only one

### PR DESCRIPTION
**Pull request by starsep**
# Rationale
I use the app mostly in the city I live in (Warsaw, Poland) - quite natural use case.
I know the city good enough that I don't really look for the public transport route if I would prefer to walk instead.
Therefore walking route is pretty much never a viable alternative - it's distracting and annoying to see it.

One possible solution would be to have "maximum walking time" as in #533 
I decided to implement something simpler which works for me: just hide the walking route if it's not the only one.

# Screenshots
Quite extreme case obviously - route between two subway stations, 11 minutes vs an hour. With the setting turned off and on.
image
image

Settings screen
image

PS I haven't created issue because I don't think it's "major work" but I can create one if needed.

### CODE REVIEW

**Comment by starsep** [comment]
I accept CLA

**Comment by ialokim** [comment]
Thanks for your contribution!

> I accept CLA

No worries, the bot will be happy once `.clabot` is on master.

@grote, what do you think of this additional option in the settings screen? I see their point.

**Comment by grote** [comment]
I agree with the rationale of this PR, but I'd wished we'd talked about this before putting in the work, because I don't think it is Transportr's job to manually change provider results like this. Instead, this should be done in PTE, or even better in Navitia which is providing these strange results. Maybe they even already have query parameters that could be added to PTE to avoid these routes there.

**Comment by starsep** [comment]
> I agree with the rationale of this PR, but I'd wished we'd talked about this before putting in the work, because I don't think it is Transportr's job to manually change provider results like this. Instead, this should be done in PTE, or even better in Navitia which is providing these strange results. Maybe they even already have query parameters that could be added to PTE to avoid these routes there.

Frankly it was easier to me to just implement this feature than wait for discussion, especially as I didn't want this annoyance to stop me from using Transportr.
I agree it should be handled by data provider if possible. I will check PTE/Navitia and see what can be done there, thanks for the great app!

**Comment by starsep** [comment]
In the end I stopped using Transportr and didn't follow up in PTE. I think it's useful feature

**Comment by Altonss** [comment]
> In the end I stopped using Transportr and didn't follow up in PTE. I think it's useful feature

No worries :) I haven't used Transportr too much lately too, but hope to be able again if development picks up speed again! We might discuss this feature in the future again (maybe also opening an issue in PTE), after more urgent issues are taken care of.

**Pull request closed without merging**
