### PR TITLE
Material Design 3 migration

### PR DESCRIPTION
**Pull request by Bnyro**
Hey,

I recently saw this project has been revived and have been really happy to see the development continue.
Since the app's current design is already some years behind the current trend, I thought it'd be awesome to start with a new, improved and more modern UI.

Therefore this PR attempts to move the app to [Material Design 3](https://m3.material.io). Please note that I haven't done any Unit or UI tests and hence can't tell if some of them are broken now (in theory there shouldn't be anything in these changes causing it!).

Please note that the changes required me to update some dependencies (AGP to 7.4.2, Material library to 1.7.0, Gradle to 7.5, appcompat to 1.5.1) and the SDK to 32. I hope there aren't any new issues coming up with that, at least from my testing it seems fine.

There are still two issues I'm fighting with and can't really figure out how to fix because I'm not that familiar with the app yet:
1. When changing the network in the navigation drawer, the UI freezes and the app crashes after some seconds. However, after restarting the app, the wanted network got selected. That's been related to the dependency updates too, fixed by downgrading some libs.
2. Now tracked in #873

I hope that changes are welcome (since I forgot to open an issue first) and that someone can test the changes or assist with the two bugs above. Of course I don't claim the changes to be perfect, but in my eyes the app looks pretty neat after applying these.

Cheers 

Edit: The screenshots below were made on Android 13, so the app uses dynamic wallpaper based colors. For Android 11 and below, the colors should be similar to the current ones as they're based on the former primary color and generated with https://m3.material.io/theme-builder.

### CODE REVIEW

**Comment by Bnyro** [comment]
(Yes, I do agree with the CLA)

**Comment by Bnyro** [comment]
Screenshot_20230612-193416_Transportr Devel
Screenshot_20230612-193421_Transportr Devel
Screenshot_20230612-193408_Transportr Devel
Screenshot_20230612-193358_Transportr Devel
Screenshot_20230612-193322_Transportr Devel
Screenshot_20230612-193309_Transportr Devel
Screenshot_20230612-193233_Transportr Devel
Screenshot_20230612-193141_Transportr Devel

**Comment by pt2121** [comment]
Thanks for the contribution. Personally, I'm glad to see the update to material 3.
Ideally, we should have a separate PR to update the compile SDK and target SDK. This would help the review.
Are you willing to create a PR for that first?

**Comment by Bnyro** [comment]
Sure, opened at #873

**Comment by Bnyro** [comment]
Update: both bugs were caused by dependency changes, downgrading them again fixed the issues.

**Comment by Bnyro** [comment]
Rebased on top of the updated dependencies from my other PR to resolve conflicts.

**Comment by pt2121** [comment]
There is a compile error in `DateUtilsTest.kt`. I haven't looked closely but I guess some resources were removed by mistake.

```
> Task :app:compileDebugUnitTestKotlin FAILED
e: /home/pt/code/forks/Transportr/app/src/test/java/de/grobox/transportr/utils/DateUtilsTest.kt: (82, 43): Unresolved reference: md_green_500
e: /home/pt/code/forks/Transportr/app/src/test/java/de/grobox/transportr/utils/DateUtilsTest.kt: (83, 43): Unresolved reference: md_red_500
```

**Comment by Bnyro** [comment]
Ah, I see!
The colors weren't removed by accident, we just don't use them anymore now.
Removed them from the tests as well, since it doesn't make sense to use them there while the app doesn't use them.

**Comment by Bnyro** [comment]
I've been trying to fix the tests, but it turns out they're failing on the master branch as well for me.

Not really sure what that's caused by, any help would be appreciated.

**Comment by newhinton** [comment]
@Bnyro Are suggestions welcome?

It is great to see someone tackle the UI migration for Transportr!

**Comment by Bnyro** [comment]
@newhinton Sure, feel free to make some proposals. However, due to the fact that I'm quite busy currently I'd also welcome if someone else implemented the improvements and I'll just merge them into my branch if they look fine.

**Comment by newhinton** [comment]
I will try to see if i can make them!


Generally, i feel the "border"-centric stlye is a bit heavy to look at. I would love to see a more colorful app, similar to what you did in libretube 0.21. The rest, like the move to "cards" and away from the "blockiness" of material 2 is great and should be kept! I will look if i can do it.

**Comment by newhinton** [comment]
image


@Bnyro I have created a PR to your branch, the above image is an example of a more colorful app!

**Comment by Bnyro** [comment]
Thank you! I will look into your changes some time at the beginning of next week, I'm not at home during the weekend unfortunately. If I forget it, please feel free to ping me again :)

**Comment by michaelblyons** [comment]
Would that be a good place to use the phone-specific accent color?

**Comment by newhinton** [comment]
> Would that be a good place to use the phone-specific accent color?

Yes! That's why i am using it ;)

The above screenshot is from an andrid emulator with Android 11 i think, that does not support material you so it defaults back to blue. I should see if i can make the default red again, so that it fits with the original theme better.

**Comment by Bnyro** [comment]
closes  #927

**Pull request closed without merging**
