### PR TITLE
Sorting algorithm for location search

### PR DESCRIPTION
**Pull request by greshake**
I'm living in Germany, using the VGS provider. I've always noticed that location search results were mindboggingly bad-sorted, that's because the API of my provider doesn't sort the results (e.g. when you searched for Town Hall, the result you actually expected was 15th place in the list, altough it is a literal match). This also introduces sorting by non-literal matches, using the Levenshtein distance. There is still much room for improvement in the search feature (caching, lazy evaluation, better sorting algorithms) but for people using providers that don't sort this is a huge improvement. 

Technical:
When collecting search suggestions, each station is added to a hashmap with a corresponding score (type Double, between 1 and 0). When displaying the new Data, the list is sorted by the updated scores.

### CODE REVIEW

**Comment by grote** [comment]
Thanks a lot for you PR! :)

My first thought - without looking too deep into the code - is that this maybe would be better done right within that `VgsProvider`. Isn't it better to fix the issues at the source instead of treating symptoms in the UI?

**Comment by XYunknown** [comment]
I considered that, but don't think so for a simple reason:
The ability to control and extend the location suggestions. The majority of time spend searching for your route is entering the desired start/end location. Any improvement in the way people enter locations is worth adding to any provider, because it adds to consistency. Some examples/ideas which might factor into a later update of the general sorting algorithm:
- faster result displaying by caching most searched/suggested locations automatically. This also reduces lagg and network traffic (the current way of making a request as soon as a character in the search box changes is not efficient.
- sorting by type of result: Stations and points of interest locations should be preferred over similar results which are just street names
- sorting favorite stations after typing only a few characters

Also, there is no need to pass similar PR's each time someone discovers the same phenomenon in a different provider, therefore making maintainance of the providers easier. Should this be implemented in more than one provider in the future, any change would be copy/paste action (buuuh!). And again, consistency of UX.

**Comment by grote** [comment]
Alright, maybe you have a point there ;)

How about creating a dedicated filter class that extends `Filter` defined in a separate file now that this class grows so much and the indentation is getting crazy?

**Comment by XYunknown** [comment]
That's absolutely doable. I'll clean this PR up in the next couple days, then you can have another look.

**Comment by XYunknown** [comment]
But for a stable release this feature still needs to be tested on some more providers- unfortunately I don't have much time myself, so we'll see how much I can contribute with testing. Just tried some other 4 providers from all over, and they seemed to work fine however.

**Comment by patkan** [comment]
@XYunknown just write here when you are ready and I can check your PR with some German and French Providers.

**Comment by XYunknown** [comment]
Cleaned up and tweaked the sorting a little, too. Ready to be tested

**Comment by patkan** [comment]
I checked with ParisProvider (Navitia), FranceNorthWest (Navitia) and VGN (EFA). I compared the current master (571996f750aa1b60e3b33f6c90155765bf968b2e) with a branch with this PR merged into it. I entered search terms into the direction search and compared loosely the propositions.

I have seen no obvious defects and the behavior was as expected (the few good values where on top of the list). To be fair these providers seem to already have sorted lists, but it seems that it does no harm to them.

If needed I can check certain aspects, otherwise I've got the impression that this PR is OK.

**Comment by XYunknown** [comment]
Any presorting by the providers will be ignored right now. If it turns out that some providers have amazingly better sorting, we could flag providers with Sorts/Does not sort and use their pre-sorting as additional input to the sorting algorithm. But for now, I think things are okay.

**Comment by patkan** [comment]
Hmm, the cases that I checked did not show that much difference. But I can imagine that there are cases in which the provider can do it better.
Maybe it would be good to enable this only if the provider is lacking a `SORTED`-capability (or however you name it)? This would have to be introduced upstream.

**Comment by XYunknown** [comment]
As said in the discussion at the beginning, consistency/maintainability would decrease in that case, and that is a scenario which has not yet been proven to even exist. If advanced sorting features are introduced (e.g. distance to the current location, whatever else) it makes the distinguishing even harder (when are the results from the provider "better"?). Further issues can be fixed in one location right now, and that prevents any further issues of the same kind to be reopened later.

**Comment by grote** [comment]
Still haven't had time to test this properly. @patkan did you also test the DbProvider? This is probably the one that most people use and that provides the good auto-completion results. We should at least make sure that these results are not worse than before.

**Comment by patkan** [comment]
No, I did not test that one. I will write if I get around to testing it.

**Comment by grote** [comment]
So, I finally made some short tests with arbitrary string. I am not completely happy with the last one "bahnhof" where it put some unimportant small addresses first.

Ideally, I'd like this PR to change to take the score returned by the API into account (if VGS always returns the same score, this shouldn't affect it) and to prefer `LocationType.STATION` over other types.

@XYunknown do you think you could do that?

Constraint: ber
=============
With PR:
------------
```
E(FAV): Berlin Hbf 
E: Bernau(b Berlin)
E: Berchtesgaden Hbf
E: Bergen auf Rügen
E: Bergholz-Rehbrücke
E: Bergheim(Erft)
E: Berghausen Am Stadion
E: Berghausen(Baden)
E: Bergen(Oberbay)
E: Bergtheim
E: Beratzhausen
E: Berghausen Pfinzbrücke
E: Bergisch Gladbach
E: Berga-Kelbra
E: Berg(Pfalz)
E: Berga(Elster)
E: Berghausen(Pfalz)
E: Bergfelde(b Berlin)
E: Bergenweiler
E: Berghausen(b Wittgenstein)
E: Bergsdorf
E: Berge(b Nauen)
E: Berbisdorf
E: Berbisdorf Anbau
E: Bergheim-Giflitz
E: Berchem(Belgien)
E: Bercher
E: Bergen op Zoom
E: Berg am Laim, München
E: Berg am Laim Bahnhof (Süd), München
E: Bergen(N)
E: Berghausen S-Bahnhof, Langenfeld (Rheinland)
E: Bergamo
E: Berghausen Am Stadion, Pfinztal
E: Berghausen Bahnhof, Pfinztal
E: Bergbahn, Lichtenhain (Bergbahn)
E: Berggeist, Murnau a. Staffelsee
E: Berchem(LUX)
E: Bergaasa station
E: Bergfrieden
E: Berettyoujfalu
E: Bergheim b.Salzburg
E: Bergheim b.Salzburg Bahnhst (Vorplatz), Österreich
E: Bergeborbeck Bahnhof, Essen (Ruhr)
E: Bergmannstraße, Dresden
E: Bergün/Bravuogn
E: Bergham b.Linz
E: Bergham b.Linz Am Dürrweg
E: Berdichev
E: Berdjausch
E: Berdsk
```
On master:
------------
```
E(FAV): Berlin Hbf
E: Bernau(b Berlin)
E: Berchtesgaden Hbf
E: Bergen auf Rügen
E: Bergholz-Rehbrücke
E: Bergheim(Erft)
E: Berghausen Am Stadion
E: Berghausen(Baden)
E: Bergen(Oberbay)
E: Bergtheim
E: Beratzhausen
E: Berghausen Pfinzbrücke
E: Bergisch Gladbach
E: Berga-Kelbra
E: Berg(Pfalz)
E: Berga(Elster)
E: Berghausen(Pfalz)
E: Bergfelde(b Berlin)
E: Bergenweiler
E: Berghausen(b Wittgenstein)
E: Bergsdorf
E: Berge(b Nauen)
E: Berbisdorf
E: Berbisdorf Anbau
E: Bergheim-Giflitz
E: Berchem(Belgien)
E: Bercher
E: Bergen op Zoom
E: Berg am Laim, München
E: Berg am Laim Bahnhof (Süd), München
E: Bergen(N)
E: Berghausen S-Bahnhof, Langenfeld (Rheinland)
E: Bergamo
E: Berghausen Am Stadion, Pfinztal
E: Berghausen Bahnhof, Pfinztal
E: Bergbahn, Lichtenhain (Bergbahn)
E: Berggeist, Murnau a. Staffelsee
E: Berchem(LUX)
E: Bergaasa station
E: Bergfrieden
E: Berettyoujfalu
E: Bergheim b.Salzburg
E: Bergheim b.Salzburg Bahnhst (Vorplatz), Österreich
E: Bergeborbeck Bahnhof, Essen (Ruhr)
E: Bergmannstraße, Dresden
E: Bergün/Bravuogn
E: Bergham b.Linz
E: Bergham b.Linz Am Dürrweg
E: Berdichev
E: Berdjausch
E: Berdsk
```

Constraint: halt
=============
With PR:
------------
```
E: Haltern am See
E: Haltingen
E: Haltingen Zentrum
E: Haltingen Markgräflerstr.
E: Haltingen Weinbergstraße
E: Haltepunkt, Niederdorf
E: Haltepunkt, Weinböhla
E: Haltepunkt Ort, Crossen an der Elster
E: Haltepunkt Lütten Klein, Rostock
E: Haltepunkt Evershagen, Rostock
E: Haltepunkt Lichtenhagen, Rostock
E: Haltepunkt Zentrum Nord, Münster (Westf)
E: Haltingen Bahnhof, Weil am Rhein
E: Haltepunkt, Jahnsdorf (Erzgebirge)
E: Haltepunkt, Niederwürschnitz
E: Haltwhistle
E: Haltepunkt Borna, Chemnitz
E: Haltepunkt, Roggentin b Rostock
E: Haltdalen
E: Haltenhoffstraße, Hannover
E: Halta Alunis
E: Haltepunkt Einen-Müssingen, Warendorf
E: Haltingen Zentrum, Weil am Rhein
E: Hainersdorf Haltepunkt Amtshainersdorf, Sebnitz
E: Halterner-/Schulstr., Marl (Westf)
E: Haltestelle, Holtgast
E: Halen
E: Halbe
E: Halle(Westf)
E: Halberstadt
E: Halle-Trotha
E: Halle Zoo
E: Halle-Neustadt
E: Halle Südstadt
E: Halle-Nietleben
E: Halle Messe
E: Haldensleben
E: Hallbergmoos
E: Halle Rosengarten
E: Halle(Saale)Hbf
E: Haldern(Rheinl)
E: Halberstadt Oststr
E: Halle-Ammendorf
E: Halle-Silberhöhe
E: Halle Steintorbrücke
E: Halle Wohnstadt Nord
E: Halle Zscherbener Straße
E: Halle(W) Gerry-Weber-Stadion
E: Halle Dessauer Brücke
E: Halle(Saale) Abzw. Zöberitz (Berliner Straße)
```
On master:
------------
```
E: Haltern am See
E: Haltingen
E: Haltingen Zentrum
E: Haltingen Markgräflerstr.
E: Haltingen Weinbergstraße
E: Halle(Saale)Hbf
E: Halberstadt
E: Halle-Ammendorf
E: Haldensleben
E: Halle(Westf)
E: Haltepunkt, Niederdorf
E: Haltepunkt, Weinböhla
E: Haltepunkt Ort, Crossen an der Elster
E: Haltepunkt Lütten Klein, Rostock
E: Haltepunkt Evershagen, Rostock
E: Haltepunkt Lichtenhagen, Rostock
E: Haltepunkt Zentrum Nord, Münster (Westf)
E: Haltingen Bahnhof, Weil am Rhein
E: Halle-Silberhöhe
E: Hallbergmoos
E: Haldern(Rheinl)
E: Haltepunkt, Jahnsdorf (Erzgebirge)
E: Halen
E: Halbe
E: Halle Südstadt
E: Halle Rosengarten
E: Halle Steintorbrücke
E: Halle-Neustadt
E: Haltepunkt, Niederwürschnitz
E: Halle Messe
E: Halle-Nietleben
E: Halle Zscherbener Straße
E: Halle-Trotha
E: Halle Wohnstadt Nord
E: Halle Dessauer Brücke
E: Halle Zoo
E: Haltwhistle
E: Haltepunkt Borna, Chemnitz
E: Haltepunkt, Roggentin b Rostock
E: Haltdalen
E: Haltenhoffstraße, Hannover
E: Halberstadt Oststr
E: Halta Alunis
E: Haltepunkt Einen-Müssingen, Warendorf
E: Haltingen Zentrum, Weil am Rhein
E: Hainersdorf Haltepunkt Amtshainersdorf, Sebnitz
E: Halle(W) Gerry-Weber-Stadion
E: Halle(Saale) Abzw. Zöberitz (Berliner Straße)
E: Halterner-/Schulstr., Marl (Westf)
E: Haltestelle, Holtgast
```

Constraint: bahnhof
=============
With PR:
------------
```
E: Ohrstedt-Bhf-N 1, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-N 3, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-N 5-9, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-N 6-19, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-N 11-13, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 1-9, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 2, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 11, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 15, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 17, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 19, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 29, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-N, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Bahnhof, Baden-Baden
E: Bahnhof, Bamberg
E: Bahnhof, Bitterfeld
E: Europcar, Bahnhofplatz 8 (Mietwagen, Plattling Bhf
E: Bahnhof, Bensheim
E: Bahnhof, Celle
E: Bahnhof, Ansbach (Mittelfranken)
E: Bahnhof, Bruchsal
E: Bahnhof, Andernach
E: Bahnhof, Böblingen
E: Bahnhof (Arena), Ludwigsburg (Württ)
E: Bahnhof, Backnang
E: Bahnhof, Bad Homburg v.d. Höhe
E: Bahnhof, Bad Hersfeld
E: Bahnhof, Angermünde
E: Bahnhof, Bad Soden am Taunus
E: Bahnhof, Bad Vilbel
E: Bahnhof, Coswig b Dresden
E: Bahnhof, Altenbeken
E: Bahnhof, Buchloe
E: Bahnhof, Bad Bevensen
E: Bahnhof, Bad Endorf
E: Bahnhof, Cham
E: Bahnhof, Bretten
E: Bahnhof, Dachau
E: Bahnhof, Bondorf
E: Bahnhof, Bühl
E: Bahnhof, Bobenheim-Roxheim
E: Bahnhof (Bus), Langerwehe
E: Bahnhof, Bergen auf Rügen
E: Linnich Bhf
E: Ostende Bhf
E: Bhfstr., Guthmannshausen
E: Heddesheim Bhf OEG
E: Dahlhausen Bhf/Ruhrmühle, Bochum
E: Oberried am Brienzersee, Bhf
E: Basel Bhfeingang Gundeldingen
E: Neuberesinchen Bhf/Bus, Frankfurt (Oder)
E: Karlshorst Bhf (S)/Wandlitzstr., Berlin
E: Zürich,Kalkbreite/Bhf.Wiedikon
E: Fischerried/Am Öferl (Bhf), Weilheim i. OB
E: Lichtenberg Bhf (S+U)/Siegfriedstr., Berlin
E: Finkenkrug Bhf/Ringstr., Falkensee
E: Lichtenberg Bhf (S+U)/Gudrunstr., Berlin
E: Alexanderplatz Bhf (S+U)/Gontardstr., Berlin
E: Alexanderplatz Bhf (S+U)/Dircksenstr., Berlin
E: Südkreuz Bhf (S)/Ostseite, Berlin
```

On master:
------------
```
E: Linnich Bhf
E: Südkreuz Bhf (S)/Ostseite, Berlin
E: Lichtenberg Bhf (S+U)/Gudrunstr., Berlin
E: Lichtenberg Bhf (S+U)/Siegfriedstr., Berlin
E: Alexanderplatz Bhf (S+U)/Dircksenstr., Berlin
E: Alexanderplatz Bhf (S+U)/Gontardstr., Berlin
E: Karlshorst Bhf (S)/Wandlitzstr., Berlin
E: Ostende Bhf
E: Neuberesinchen Bhf/Bus, Frankfurt (Oder)
E: Zürich,Kalkbreite/Bhf.Wiedikon
E: Heddesheim Bhf OEG
E: Finkenkrug Bhf/Ringstr., Falkensee
E: Fischerried/Am Öferl (Bhf), Weilheim i. OB
E: Dahlhausen Bhf/Ruhrmühle, Bochum
E: Oberried am Brienzersee, Bhf
E: Ohrstedt-Bhf-N 1, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-N 3, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-N 5-9, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-N 6-19, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-N 11-13, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 1-9, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 2, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 11, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 15, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 17, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 19, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S 29, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-N, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Ohrstedt-Bhf-S, Wester-Ohrstedt - Ohrstedt-Bahnhof
E: Basel Bhfeingang Gundeldingen
E: Bahnhof, Baden-Baden
E: Bahnhof, Bamberg
E: Bahnhof, Bitterfeld
E: Bhfstr., Guthmannshausen
E: Europcar, Bahnhofplatz 8 (Mietwagen, Plattling Bhf
E: Bahnhof, Bensheim
E: Bahnhof, Celle
E: Bahnhof, Ansbach (Mittelfranken)
E: Bahnhof, Bruchsal
E: Bahnhof, Andernach
E: Bahnhof, Böblingen
E: Bahnhof (Arena), Ludwigsburg (Württ)
E: Bahnhof, Backnang
E: Bahnhof, Bad Homburg v.d. Höhe
E: Bahnhof, Bad Hersfeld
E: Bahnhof, Angermünde
E: Bahnhof, Bad Soden am Taunus
E: Bahnhof, Bad Vilbel
E: Bahnhof, Coswig b Dresden
E: Bahnhof, Altenbeken
E: Bahnhof, Buchloe
E: Bahnhof, Bad Bevensen
E: Bahnhof, Bad Endorf
E: Bahnhof, Cham
E: Bahnhof, Bretten
E: Bahnhof, Dachau
E: Bahnhof, Bondorf
E: Bahnhof, Bühl
E: Bahnhof, Bobenheim-Roxheim
E: Bahnhof (Bus), Langerwehe
E: Bahnhof, Bergen auf Rügen
```

**Comment by XYunknown** [comment]
Not sure what you are thinking of. Do we have access to (internal) scoring data from the API's? The only information we get is, afaik, the ordering of the API results. In making this PR I assumed that this order is sometimes broken. To differentiate would again require tagging of API's as 'sorts results' and 'does not sort results', again leading to different user experiences based on location and more maintaining requirements. Maybe due to the time span this PR has been pending now, we are kind of circling in our arguments. 

Concerning the other issue you mentioned, I'll check the code again, because I thought I had that issue sorted out already.

**Comment by grote** [comment]
> Not sure what you are thinking of. Do we have access to (internal) scoring data from the API's? The only information we get is, afaik, the ordering of the API results.

Check out the `SuggestedLocation` class from PTE. This is returned by the API and includes a priority (which is used to sort the list locations).

> Concerning the other issue you mentioned, I'll check the code again, because I thought I had that issue sorted out already.

Thanks!

**Comment by grote** [comment]
@XYunknown did you have a look at the priorities returned from the API?

I am doing a major refactoring (almost a rewrite) for Transportr 2 and this PR will be increasingly difficult to apply cleanly. But there's still time, so please let me know.

**Comment by grote** [comment]
@XYunknown I refactored the `LocationView` yesterday. This PR now has conflicts, but should be much easier to do than before. There's already a standalone filter that you can use.

Once schildbach/public-transport-enabler#140 gets merged, I will also expose the SuggestedLocations to the filter, so you have the priority to work with.

**Comment by grote** [comment]
The location score as returned by PTE is now available here in this `Filter`: https://github.com/grote/Transportr/blob/master/src/de/grobox/liberario/locations/SuggestLocationsFilter.java

**Comment by XYunknown** [comment]
I'll try to do it asap, but I'm kinda busy this week. Maybe I can squeeze it in tonight or tomorrow.

**Comment by XYunknown** [comment]
Okay, I've looked at SuggestedLocation. Turns out it is also a much more natural place to sort the results, it's already being done there anyway. But unfortunately, I've looked at the 'priority' values and it turns out they might be chosen very arbitrarily. With VGS, I searched for 'Mensa' hoping for the result 'Universität Mensa' but got 'Name' as first result and the one I was looking for at 20th place. Against all rational consideration, the priority of 'Name' was over 11000, and the priority of 'Universität Mensa' 99. Even truncating the value may not help, I just don't know how to get the values into reasonable relation with other metrics. Not if we want a general solution. So, maybe after all a 'priority override' would be the best solution, where we can tag providers which don't use sensible presorting and we can do it by ourselves...

**Comment by grote** [comment]
You might want to open an issue against PTE regarding the weird priorities. Would be interesting to know whether they are returned like this by their API. The priority 11000 suggests a bug in the `VgsProvider`.

**Comment by XYunknown** [comment]
I've investigated that possiblity, but these are the actual values returned by the API.

**Comment by grote** [comment]
I am closing this as the underlying codebase has changed significantly in the meantime.

**Pull request closed without merging**
