### PR TITLE
update pte

### PR DESCRIPTION
**Pull request by patkan**
* various fixes in AbstractProviders
* changes in API_BASE for VGN, DING, HSL, TLEM
* remove the dead provider in Transportr
* remove the "secret" for VGN as this is not needed anymore due to the PTE-update

### CODE REVIEW

**Comment by grote** [comment]
Thanks a lot! :)

Any of these removed providers have drawables that need to be removed as well?

**Comment by patkan** [comment]
Thanks, forgot to check the drawables :-) I will update my PR.

**Comment by grote** [comment]
Thanks, the source file in art/networks is probably not needed anymore as well.

**Comment by patkan** [comment]
Well, it's still in the git if we need it.
PACA had no drawable, neither could I find ATC, so this should be all of them.

**Pull request merged**
