### PR TITLE
add VRN & VVS logos

### PR DESCRIPTION
**Pull request by dotlambda**
I just took the files from Wikimedia and resized them

### CODE REVIEW

**Comment by grote** [comment]
Thanks a lot! Normally, I like transparent backgrounds, but here this will cause problems with dark/light themes. So it would be better to use a white background instead.

**Comment by dotlambda** [comment]
sorry for that, I added white backgrounds

**Comment by dotlambda** [comment]
By the way, how about mentioning that on https://transportr.grobox.de/#contribute?
I couldn't find a github repo of the site (how about setting one up?), otherwise I would have added it myself.

**Comment by grote** [comment]
Thanks a lot! I am looking forward to your next contribution! :)

Btw. I added the background information to the homepage.

**Pull request closed without merging**
