### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by Montagnard65**
I modified lines 257 and 258, to add Lyon in the french East description, and the "TCL" network.

### CODE REVIEW

**Comment by grote** [comment]
Thanks, looks good! :)

**Comment by Montagnard65** [comment]
Great! Your Welcome! When do you think, Transportr could be available with Lyon's transport data ?

**Comment by grote** [comment]
I am not sure I understand the question. It should already work in Lyon.

**Comment by Montagnard65** [comment]
Sorry for my (stupid) question, I though this improvement was required to have Lyon public transport working (I didn't try since my first thread)...
By the way, could Transportr can integrate open data of public's bikes (location and availability for exemple) ? Could Transportr can integrate real time position of public transports (real position of bus, metro, tram, etc ; quick refreshment and lot of data) to update the time of the next stop ?

**Comment by grote** [comment]
> I though this improvement was required to have Lyon public transport working

No, what you did was just updating the description, after support for Lyon had been added.

> By the way, could Transportr can integrate open data of public's bikes (location and availability for exemple) ?

It could, but it is difficult and lots of work.

> Could Transportr can integrate real time position of public transports (real position of bus, metro, tram, etc ; quick refreshment and lot of data) to update the time of the next stop ?

It does this already when this data is available. Lyon data comes from Navitia, so they would need to have realtime data and expose it via their API. Research especially on the latter is welcome.

**Comment by Montagnard65** [comment]
Hi,
For information, I asked one developper of Navitia and he told me they are interessed by real time tranport data (this data are available for Lyon), but they haven't planened yet to integer it in their plateform.

**Comment by grote** [comment]
Thanks for finding this out, let us know when you have some news!

**Comment by Montagnard65** [comment]
With pleasure ! ;-)

**Pull request merged**
