### PR TITLE
Logo of BCN's MTA

### PR DESCRIPTION
**Pull request by yopaseopor**
This is the logo for a Barcelona's (Spain) and area network. It is the logo for the Metropolitan Transport Authority (Autoritat del Transport Metropolità)

### CODE REVIEW

**Comment by yopaseopor** [comment]
I accept the Contributor License Agreement

**Comment by grote** [comment]
Hey, thanks for your pull request! I don't really see a point about adding a Barcelona icon as long as we don't have a dedicated `BarcelonaProvider`.

**Comment by yopaseopor** [comment]
I hope we will have it soon ;)
For this reason also the Catalan translation is all done.

**Comment by grote** [comment]
I still think it would be better to add the logo together with a provider in one single PR. No need to include it before we have a provider.

**Pull request closed without merging**
