### PR TITLE
Add Czechia provider

### PR DESCRIPTION
**Pull request by sideeffffect**

### CODE REVIEW

**Comment by sideeffffect** [comment]
@cla-bot yes, I accept.
I've already added myself to the list, what more do you want from me you stupid robot?

**Comment by sideeffffect** [comment]
blocked on https://gitlab.com/opentransitmap/public-transport-enabler/merge_requests/4

**Comment by grote** [comment]
Thanks a lot for your PR and sorry about the bot! It is too stupid to see that you added yourself to the file as it checks only master.

The PR looks good, but the CI fails. Did you maybe reference the wrong commit ID for PTE in build.gradle?

**Comment by sideeffffect** [comment]
Yes, CI is read. That's because the `public-transport-enabler` fork is broken.

see my comment above: https://github.com/grote/Transportr/pull/644#issuecomment-552138533

**Comment by grote** [comment]
@ialokim do you know why the NetworkId for the Czech provider is different in your fork?

**Comment by ialokim** [comment]
> @ialokim do you know why the NetworkId for the Czech provider is different in your fork?

I'm sorry, it seems there has been a problem while performing the last manual merge. I've finally found some time to merge it now, so after upgrading to the new PTE version in Transportr it should work again.

**Comment by sideeffffect** [comment]
we have a green build :tada:

**Comment by grote** [comment]
Thanks for your patience!

**Pull request merged**
