### PR TITLE
Logo ZVV

### PR DESCRIPTION
**Pull request by tenminutemail**

### CODE REVIEW

**Comment by tenminutemail** [comment]
Updated.

**Comment by grote** [comment]
Thanks, but sorry I forget. It would be nice to have the source SVG here as well, in case we have need to make changes to that logo.

**Comment by tenminutemail** [comment]
@grote Just did a PR to add the SVG, as uploads are not possible

**Comment by tenminutemail** [comment]
@grote Added SVG

**Comment by grote** [comment]
Merged, thanks!

**Pull request closed without merging**
