### PR TITLE
Added missing network logos

### PR DESCRIPTION
**Pull request by vinzv**
* Verkehrsgesellschaft Mecklenburg-Vorpommern
* Nahverkehrsverbund Schleswig-Holstein
* Verkehrsverbund Oberelbe
* Verkehrsverbund Mittelsachsen
* Märkische Verkehrsgesellschaft
* Nordhessischer Verkehrsverbund
* Nahverkehrsgesellschaft Baden-Württemberg
* Verkehrsverbund Vogtland
* Verkehrsmanagement-Gesellschaft Saar

Both PNG binaries and SVG sources included. All logos are public domain,
data taken from Wikipedia.

### CODE REVIEW

**Comment by grote** [comment]
Awesome work @vinzv ! :)

We are just discussing using vector drawables instead of pngs in #173 where there are already some of the ones you did. Do you think you could turn your SVGs into vector drawables like described there and use them instead of the PNGs?

**Comment by vinzv** [comment]
Just created them with SVG to VectorDrawable Converter and --lib BetterVectorDrawable. As I have no Android Dev Setup running here it's a blind shot. Hopefully the files work.

**Comment by grote** [comment]
The "BetterVectorDrawable" lib won't work as this is a special library which I am not using. You don't need special parameters. There's only drawables with "hollow paths" like the middle of the letter "O" which can cause problems. There, the "--fix-fill-type" option might help.

**Comment by grote** [comment]
Some more comments: All file names should be of the form `network_[NetworkId]_logo.[ext]`
Files with the extension `xml` need to be placed in `res/drawable` and files with `svg` should be in `art/networks`. When there is XML files for each logo, the PNG files are not needed anymore and should be deleted.

**Comment by vinzv** [comment]
I re-created the XML files. The only warnings I got were:
`..
[Warning(s)] met.svg: Met unsupported element(s): rect.
..
[Warning(s)] network_avv_logo.svg: Met unsupported element(s): rect.
.
[Warning(s)] network_db_logo.svg: Met unsupported element(s): rect.
.......
[Warning(s)] network_vms_logo.svg: Met unsupported element(s): polygon.
....
[Warning(s)] ontario.svg: Met unsupported element(s): rect, text.`

**Comment by grote** [comment]
The files that caused warning are having display problems. Usually, you should be able to solve that by transforming the problematic objects into paths. Inkscape -> Objects to Path.

As discussed in #173 the SVG files need an explicit white background which has exactly the same dimensions as the file. See the network_db_logo.svg as an example.

Sorry for all those comments, but we need to get this right, right? ;)

**Comment by grote** [comment]
Also, looks like there's still PNGs in your PR which are also available as XML files. These need to be deleted, because the XML is not used, if there is a PNG.

**Comment by grote** [comment]
One more thing ;)
The maximum size should be 64dp. This can be edited manually in the XML file. For quadratic images this means:
```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="64dp"
    android:height="64dp"
```

**Comment by vinzv** [comment]
As I'm not on a Windows machine now and don't want to install Mono I used https://inloop.github.io/svg2android/ for conversion.
All XML files have 64dp now and a explicit white background. Hopefully the files work now.

**Comment by grote** [comment]
Thanks a lot. This is looking great!

I just tried this out and noticed some small issues:
* You overwrote the existing and already correct `res/drawable/network_db_logo.xml` with something that has no background
* Many/All XML logos have duplicated attributes, such as `android:width` and `android:pathData`
* Many/All XML logos have no white background
* The invg logo xml is a broken DB logo
* MVG XML has no white background
* MVV XML is on the head and has no white background
* NAH SH still has a PNG, the XML is broken probably due to using the unsupported path fill option
* NVBW looks like it is the same as NAH SH, same for NVBW (I think the website might not always update the XML text)
* Ontario logo has no text, but the SVG is outdated, @chimo didn't update it when he changed the logo, I think.

I'll stop here, because I think many issues will be taken care of when converting the SVGs properly. Then, I'll check again.

**Comment by grote** [comment]
I checked the SVGs and I think the reason why the white background isn't shown is because it used the unsupported fill rule.

There's an explanation here for how to fix this: https://github.com/a-student/SvgToVectorDrawableConverter#manual-editing
Basically, you need to select the icon in the top-right when filling areas:

Inkscape

**Pull request closed without merging**
